# Generated by Django 2.0.3 on 2019-02-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
