# Generated by Django 2.0.3 on 2019-02-14 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloglist', '0004_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvote',
        ),
    ]
